<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
class SEH_Settings {
    const OPTION = 'seh_options';
    public function __construct() { add_action( 'admin_menu', array( $this, 'menu' ) ); add_action( 'admin_init', array( $this, 'register' ) ); }
    public function defaults() { return array(
        'logo_id'=>'','logo_width'=>'140','logo_height'=>'40','logo_text'=>'Shop','logo_link'=>home_url('/'),
        'sticky'=>'1','max_width'=>'1200','height'=>'72','padding_desktop'=>'16px 24px','padding_mobile'=>'12px 16px','bg'=>'#ffffff','border'=>'#e8e8ee','shadow'=>'1',
        'menu_id'=>'','menu_color'=>'#111827','menu_hover'=>'#2563eb','menu_font_size'=>'15','menu_font_weight'=>'600','dropdown'=>'1','dropdown_bg'=>'#ffffff','dropdown_text'=>'#111827','dropdown_hover'=>'#2563eb',
        'search_icon'=>'1','account_icon'=>'1','wishlist_icon'=>'1','cart_icon'=>'1','icon_size'=>'22','icon_color'=>'#111827','icon_hover'=>'#2563eb','badge_bg'=>'#2563eb','badge_text'=>'#ffffff',
        'search_dropdown'=>'1','search_placeholder'=>'Search for products, brands and more...','popular_searches'=>'Wireless Headphones, Smart Watch, Sneakers, Backpack','show_popular'=>'1','trending_products'=>'1','search_bg'=>'#ffffff','search_border'=>'#d1d5db','search_button'=>'#111827',
        'cart_drawer'=>'1','cart_width'=>'420','cart_bg'=>'#ffffff','cart_button_text'=>'View Cart','checkout_button_text'=>'Checkout','show_subtotal'=>'1','shipping_text'=>'Shipping calculated at checkout.','qty_controls'=>'1','remove_item'=>'1',
        'trust_bar'=>'0','trust_bg'=>'#f8fafc','trust_text'=>'#111827','trust1_title'=>'Free Shipping','trust1_subtitle'=>'On eligible orders','trust2_title'=>'30-Day Returns','trust2_subtitle'=>'Easy returns','trust3_title'=>'Secure Payment','trust3_subtitle'=>'Protected checkout',
        'mobile_header'=>'1','mobile_logo_position'=>'left','hamburger'=>'1','mobile_search'=>'1','mobile_bg'=>'#ffffff','mobile_text'=>'#111827'
    ); }
    public function get_options() { return wp_parse_args( get_option( self::OPTION, array() ), $this->defaults() ); }
    public function get( $key ) { $o=$this->get_options(); return $o[$key] ?? ''; }
    public function menu() { add_options_page( __( 'Simple Header', 'simple-ecommerce-header' ), __( 'Simple Header', 'simple-ecommerce-header' ), 'manage_options', 'simple-ecommerce-header', array( $this, 'page' ) ); }
    public function register() { register_setting( 'seh_settings', self::OPTION, array( 'sanitize_callback'=>array($this,'sanitize') ) ); }
    public function sanitize( $in ) { $d=$this->defaults(); $out=array(); foreach($d as $k=>$v){ $val=$in[$k] ?? ''; if (strpos($k,'color')!==false||in_array($k,array('bg','border','menu_color','menu_hover','dropdown_bg','dropdown_text','dropdown_hover','icon_color','icon_hover','badge_bg','badge_text','search_bg','search_border','search_button','cart_bg','trust_bg','trust_text','mobile_bg','mobile_text'),true)) $out[$k]=sanitize_hex_color($val) ?: $v; elseif (in_array($k,array('logo_link'),true)) $out[$k]=esc_url_raw($val); elseif (in_array($k,array('logo_id','logo_width','logo_height','max_width','height','menu_id','menu_font_size','icon_size','cart_width'),true)) $out[$k]=absint($val); elseif (in_array($k,array('sticky','shadow','dropdown','search_icon','account_icon','wishlist_icon','cart_icon','search_dropdown','show_popular','trending_products','cart_drawer','show_subtotal','qty_controls','remove_item','trust_bar','mobile_header','hamburger','mobile_search'),true)) $out[$k]=empty($val)?'0':'1'; elseif ($k==='mobile_logo_position') $out[$k]=in_array($val,array('left','center'),true)?$val:'left'; else $out[$k]=sanitize_text_field($val); } return $out; }
    private function field($key,$label,$type='text'){ $o=$this->get_options(); printf('<label><span>%s</span><input type="%s" name="%s[%s]" value="%s"></label>',esc_html($label),esc_attr($type),esc_attr(self::OPTION),esc_attr($key),esc_attr($o[$key])); }
    private function checkbox($key,$label){ $o=$this->get_options(); printf('<label class="seh-check"><input type="checkbox" name="%s[%s]" value="1" %s> %s</label>',esc_attr(self::OPTION),esc_attr($key),checked($o[$key],'1',false),esc_html($label)); }
    public function page(){ if(!current_user_can('manage_options')) return; $o=$this->get_options(); $menus=wp_get_nav_menus(); ?>
    <div class="wrap seh-admin"><h1><?php esc_html_e('Simple Ecommerce Header','simple-ecommerce-header'); ?></h1><form method="post" action="options.php"><?php settings_fields('seh_settings'); ?>
    <h2><?php esc_html_e('Customization Options','simple-ecommerce-header'); ?></h2><div class="seh-grid">
    <?php $this->field('logo_id','Logo attachment ID','number'); $this->field('logo_width','Logo width','number'); $this->field('logo_height','Logo height','number'); $this->field('logo_text','Logo text fallback'); $this->field('logo_link','Logo link URL','url'); $this->checkbox('sticky','Enable sticky header'); $this->field('max_width','Header max width','number'); $this->field('height','Header height','number'); $this->field('padding_desktop','Header padding desktop'); $this->field('padding_mobile','Header padding mobile'); $this->field('bg','Header background color','color'); $this->field('border','Header border color','color'); $this->checkbox('shadow','Header shadow'); ?>
    <label><span><?php esc_html_e('Select WordPress menu','simple-ecommerce-header'); ?></span><select name="<?php echo esc_attr(self::OPTION); ?>[menu_id]"><option value="">—</option><?php foreach($menus as $m) printf('<option value="%d" %s>%s</option>',$m->term_id,selected($o['menu_id'],$m->term_id,false),esc_html($m->name)); ?></select></label>
    <?php foreach(array('menu_color'=>'Menu text color','menu_hover'=>'Menu hover color','menu_font_size'=>'Menu font size','menu_font_weight'=>'Menu font weight','dropdown_bg'=>'Dropdown background color','dropdown_text'=>'Dropdown text color','dropdown_hover'=>'Dropdown hover color','icon_size'=>'Icon size','icon_color'=>'Icon color','icon_hover'=>'Icon hover color','badge_bg'=>'Badge background color','badge_text'=>'Badge text color','search_placeholder'=>'Search placeholder text','popular_searches'=>'Popular search keywords','search_bg'=>'Search panel background color','search_border'=>'Search input border color','search_button'=>'Search button color','cart_width'=>'Cart drawer width','cart_bg'=>'Cart drawer background color','cart_button_text'=>'Cart button text','checkout_button_text'=>'Checkout button text','shipping_text'=>'Shipping text','trust_bg'=>'Trust bar background color','trust_text'=>'Trust bar text color','trust1_title'=>'Trust item 1 title','trust1_subtitle'=>'Trust item 1 subtitle','trust2_title'=>'Trust item 2 title','trust2_subtitle'=>'Trust item 2 subtitle','trust3_title'=>'Trust item 3 title','trust3_subtitle'=>'Trust item 3 subtitle','mobile_bg'=>'Mobile menu background color','mobile_text'=>'Mobile menu text color') as $k=>$l) $this->field($k,$l, strpos($k,'color')!==false||in_array($k,array('trust_bg','trust_text','mobile_bg','mobile_text','cart_bg'),true)?'color':'text'); foreach(array('dropdown'=>'Enable dropdown menu','search_icon'=>'Enable search icon','account_icon'=>'Enable account icon','wishlist_icon'=>'Enable wishlist icon','cart_icon'=>'Enable cart icon','search_dropdown'=>'Enable search dropdown','show_popular'=>'Show popular searches','trending_products'=>'Show trending products','cart_drawer'=>'Enable cart drawer','show_subtotal'=>'Show subtotal','qty_controls'=>'Enable quantity controls','remove_item'=>'Enable remove item button','trust_bar'=>'Enable trust bar','mobile_header'=>'Enable mobile header','hamburger'=>'Enable hamburger menu','mobile_search'=>'Enable mobile search bar') as $k=>$l) $this->checkbox($k,$l); ?>
    <label><span>Mobile logo position</span><select name="<?php echo esc_attr(self::OPTION); ?>[mobile_logo_position]"><option value="left" <?php selected($o['mobile_logo_position'],'left'); ?>>Left</option><option value="center" <?php selected($o['mobile_logo_position'],'center'); ?>>Center</option></select></label></div><?php submit_button(); ?></form></div><?php }
}
