<?php if ( ! defined( 'ABSPATH' ) ) { exit; } $o=$settings->get_options(); $logo=$o['logo_id']?wp_get_attachment_image_url($o['logo_id'],'full'):''; ?>
<div class="seh-wrap <?php echo $o['sticky']==='1'?'seh-sticky':''; ?>" style="--seh-primary-color:<?php echo esc_attr($o['icon_color']); ?>;--seh-accent-color:<?php echo esc_attr($o['icon_hover']); ?>;--seh-bg-color:<?php echo esc_attr($o['bg']); ?>;--seh-text-color:<?php echo esc_attr($o['menu_color']); ?>;--seh-border-color:<?php echo esc_attr($o['border']); ?>;--seh-max-width:<?php echo absint($o['max_width']); ?>px;--seh-height:<?php echo absint($o['height']); ?>px;--seh-pad-desktop:<?php echo esc_attr($o['padding_desktop']); ?>;--seh-pad-mobile:<?php echo esc_attr($o['padding_mobile']); ?>;--seh-icon-size:<?php echo absint($o['icon_size']); ?>px;--seh-badge-bg:<?php echo esc_attr($o['badge_bg']); ?>;--seh-badge-text:<?php echo esc_attr($o['badge_text']); ?>;--seh-dropdown-bg:<?php echo esc_attr($o['dropdown_bg']); ?>;--seh-dropdown-text:<?php echo esc_attr($o['dropdown_text']); ?>;--seh-dropdown-hover:<?php echo esc_attr($o['dropdown_hover']); ?>;--seh-mobile-bg:<?php echo esc_attr($o['mobile_bg']); ?>;--seh-mobile-text:<?php echo esc_attr($o['mobile_text']); ?>;">
  <header class="seh-header <?php echo $o['shadow']==='1'?'has-shadow':''; ?>" role="banner"><div class="seh-inner">
    <?php if($o['hamburger']==='1'): ?><button class="seh-icon seh-mobile-toggle" aria-label="<?php esc_attr_e('Open menu','simple-ecommerce-header'); ?>" aria-expanded="false" data-seh-toggle="mobile">☰</button><?php endif; ?>
    <a class="seh-logo seh-logo-<?php echo esc_attr($o['mobile_logo_position']); ?>" href="<?php echo esc_url($o['logo_link']); ?>"><?php if($logo): ?><img src="<?php echo esc_url($logo); ?>" width="<?php echo absint($o['logo_width']); ?>" height="<?php echo absint($o['logo_height']); ?>" alt="<?php echo esc_attr($o['logo_text']); ?>"><?php else: ?><span><?php echo esc_html($o['logo_text']); ?></span><?php endif; ?></a>
    <nav class="seh-nav" aria-label="<?php esc_attr_e('Primary menu','simple-ecommerce-header'); ?>"><?php wp_nav_menu(array('menu'=>$o['menu_id'],'container'=>false,'fallback_cb'=>array('SEH_Walker_Fallback','menu'),'menu_class'=>'seh-menu','depth'=>$o['dropdown']==='1'?3:1)); ?></nav>
    <div class="seh-actions">
      <?php if($o['search_icon']==='1'): ?><button class="seh-icon" aria-label="<?php esc_attr_e('Open search','simple-ecommerce-header'); ?>" aria-expanded="false" data-seh-toggle="search">⌕</button><?php endif; ?>
      <?php if($o['account_icon']==='1'): ?><a class="seh-icon" aria-label="<?php esc_attr_e('Account','simple-ecommerce-header'); ?>" href="<?php echo esc_url($woo->account_url()); ?>">♙</a><?php endif; ?>
      <?php if($o['wishlist_icon']==='1'): ?><a class="seh-icon seh-badge-wrap" aria-label="<?php esc_attr_e('Wishlist','simple-ecommerce-header'); ?>" href="<?php echo esc_url(home_url('/wishlist/')); ?>">♡<span class="seh-badge">0</span></a><?php endif; ?>
      <?php if($o['cart_icon']==='1'): ?><button class="seh-icon seh-badge-wrap" aria-label="<?php esc_attr_e('Open cart','simple-ecommerce-header'); ?>" aria-expanded="false" data-seh-toggle="cart">🛒<span class="seh-badge seh-cart-count"><?php echo esc_html($woo->count()); ?></span></button><span class="seh-subtotal"><?php echo wp_kses_post($woo->subtotal()); ?></span><?php endif; ?>
    </div>
  </div></header>
  <?php if($o['trust_bar']==='1'): ?><div class="seh-trust" style="background:<?php echo esc_attr($o['trust_bg']); ?>;color:<?php echo esc_attr($o['trust_text']); ?>"><span><strong><?php echo esc_html($o['trust1_title']); ?></strong> <?php echo esc_html($o['trust1_subtitle']); ?></span><span><strong><?php echo esc_html($o['trust2_title']); ?></strong> <?php echo esc_html($o['trust2_subtitle']); ?></span><span><strong><?php echo esc_html($o['trust3_title']); ?></strong> <?php echo esc_html($o['trust3_subtitle']); ?></span></div><?php endif; ?>
  <?php include SEH_PATH.'templates/search-dropdown.php'; include SEH_PATH.'templates/mobile-menu.php'; include SEH_PATH.'templates/cart-drawer.php'; ?>
</div>
